# Generated by Django 4.2 on 2023-04-22 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='managecategory',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
