# Generated by Django 4.2 on 2023-04-24 06:06

from django.db import migrations
import encrypted_field.fields


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0006_alter_educationlevel_city_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='educationlevel',
            name='state',
            field=encrypted_field.fields.EncryptedField(),
        ),
    ]
